// Content for the static treatment pages. General patient education only:
// no outcome statistics, equipment names, prices or doctor credentials.

export const TREATMENTS = {
  'robotic-knee-replacement': {
    name: 'Robotic Knee Replacement',
    h1: 'Robotic Knee Replacement in Jodhpur',
    metaTitle: 'Robotic Knee Replacement in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Learn how robotic-assisted knee replacement works, who may be a candidate, what recovery involves and how to consult an orthopaedic surgeon in Jodhpur.',
    cardText: 'Knee replacement planned and performed with robotic assistance for precise implant positioning.',
    bodyLocation: 'Knee',
    image: null,
    imageAlt: '',
    intro:
      'Robotic-assisted knee replacement combines an experienced orthopaedic surgeon with computer-guided technology to help plan and position a knee implant. Learn how it works and whether it may be suitable for you.',
    overview: [
      'In a knee replacement, worn or damaged joint surfaces are removed and replaced with artificial components. In a robotic-assisted procedure, the surgeon uses a computer-based system to map the knee, create a surgical plan and guide bone preparation within set boundaries.',
      'The robot does not operate on its own. Every step is controlled by the surgeon; the technology acts as a tool that supports planning and accuracy. Robotic assistance can be used for total knee replacement and, in suitable patients, partial knee replacement.',
      'Whether robotic assistance is right for you depends on your diagnosis, the pattern of damage in your knee, your general health and your surgeon’s assessment. Please ask our team about the options currently available at the hospital.',
    ],
    whoBenefits: [
      'People with advanced knee arthritis that limits walking, climbing stairs or sleep',
      'Patients whose pain continues despite medicines, physiotherapy, weight management or injections',
      'Patients with knee deformity, such as bow-legs or knock-knees, linked to joint wear',
      'People who have been advised knee replacement and want to understand all available techniques',
    ],
    symptomsTitle: 'Conditions and Symptoms That May Lead to Evaluation',
    symptomsIntro: 'Robotic knee replacement is usually discussed only after a detailed orthopaedic assessment.',
    symptoms: [
      'Persistent knee pain while walking, standing or at rest',
      'Morning stiffness or difficulty bending and straightening the knee',
      'Swelling that keeps coming back',
      'Grinding, clicking or a feeling of the knee giving way',
      'Osteoarthritis, rheumatoid arthritis or arthritis after an old injury',
      'Visible change in leg alignment over time',
    ],
    procedureTitle: 'How Robotic-Assisted Knee Replacement Works',
    procedureIntro: 'A simplified overview. Your surgeon will explain the exact plan for your case.',
    procedure: [
      { title: 'Assessment and imaging', text: 'Your doctor reviews your history, examines the knee and studies X-rays or other scans to confirm the diagnosis and plan treatment.' },
      { title: 'Personalised surgical plan', text: 'Using imaging and in-theatre measurements, a three-dimensional plan of your knee is created to decide implant size, position and alignment.' },
      { title: 'Surgeon-controlled bone preparation', text: 'During surgery the surgeon guides the robotic arm or instrument, which helps keep bone cuts within the planned area.' },
      { title: 'Implant placement and balancing', text: 'The new components are fitted and the surgeon checks movement and soft-tissue balance before closing the wound.' },
    ],
    benefits: [
      { title: 'Detailed planning', text: 'Pre-operative mapping can help the surgeon plan implant size and position for your individual knee.' },
      { title: 'Precise bone preparation', text: 'Guided boundaries are designed to support accurate cuts and help protect surrounding soft tissue.' },
      { title: 'Alignment and balance', text: 'Real-time feedback can help the surgeon assess joint balance during the operation.' },
    ],
    recovery: [
      'Recovery after robotic-assisted knee replacement follows the same principles as conventional knee replacement. Many patients begin assisted walking and gentle exercises soon after surgery under the guidance of the care team.',
      'The pace of recovery varies with age, general health, pre-surgery fitness and how closely the rehabilitation plan is followed. Your surgeon and physiotherapist will set goals that suit you.',
    ],
    aftercare: [
      'Follow your physiotherapy programme regularly',
      'Keep the wound clean and dry as advised',
      'Take prescribed medicines exactly as directed',
      'Use a walker or stick until your team advises otherwise',
      'Attend all follow-up appointments',
      'Report fever, increasing redness, calf pain or unusual swelling promptly',
    ],
    whenToConsult: [
      'Knee pain has lasted for weeks or months and limits daily activities',
      'Pain disturbs your sleep',
      'Non-surgical treatment is no longer giving relief',
      'You have been told you may need a knee replacement and want an opinion on robotic assistance',
    ],
    faqs: [
      { q: 'Does a robot perform the knee replacement?', a: 'No. The orthopaedic surgeon performs the operation. The robotic system is a tool that helps with planning and guiding bone preparation; the surgeon remains in control throughout.' },
      { q: 'Is robotic knee replacement suitable for everyone?', a: 'Not always. Suitability depends on your diagnosis, knee anatomy, overall health and your surgeon’s assessment. A consultation is needed to decide the best approach.' },
      { q: 'How is it different from conventional knee replacement?', a: 'The implant and the goals are similar. The difference is the computer-assisted planning and guidance used to help position the implant.' },
      { q: 'Will I need physiotherapy afterwards?', a: 'Yes. Rehabilitation is an important part of recovery after any knee replacement, including robotic-assisted surgery.' },
      { q: 'How do I find out if robotic knee replacement is available for me?', a: 'Book a consultation or contact the hospital. The team can confirm current availability and review whether it is appropriate for your knee.' },
    ],
    related: ['knee-replacement', 'hip-replacement', 'arthroscopy-sports-injury'],
    ctaTitle: 'Discuss Robotic Knee Replacement With Our Team',
  },

  'knee-replacement': {
    name: 'Knee Replacement',
    h1: 'Knee Replacement Surgery in Jodhpur',
    metaTitle: 'Knee Replacement Surgery in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Explore knee replacement in Jodhpur: total and partial procedures, joint implants, evaluation, rehabilitation and questions to discuss with your surgeon.',
    cardText: 'Replacement of damaged knee joint surfaces to help reduce pain and improve movement.',
    bodyLocation: 'Knee',
    image: null,
    imageAlt: '',
    intro:
      'Knee replacement surgery resurfaces a damaged knee joint with artificial components. It may be considered when arthritis or joint damage causes ongoing pain and stiffness that other treatments no longer control.',
    overview: [
      'The knee is where the thigh bone (femur), shin bone (tibia) and kneecap (patella) meet. Smooth cartilage covers these surfaces so they glide easily. When cartilage wears away, bone can rub on bone, causing pain, swelling and stiffness.',
      'During knee replacement, the damaged surfaces are removed and capped with implants, usually made of metal alloys and medical-grade plastic. In a total knee replacement all main surfaces are resurfaced; in a partial (unicompartmental) replacement only the worn section is replaced.',
      'Surgery is usually recommended only after non-surgical options such as medicines, physiotherapy, weight management, supports or injections have been tried, or when joint damage is advanced.',
    ],
    whoBenefits: [
      'People with knee osteoarthritis causing daily pain',
      'Patients with rheumatoid or other inflammatory arthritis affecting the knee',
      'People with joint damage after a previous injury or fracture',
      'Patients whose quality of life is limited by knee stiffness or deformity',
    ],
    symptomsTitle: 'Signs Your Knee May Need Evaluation',
    symptomsIntro: 'These symptoms do not automatically mean surgery, but they deserve an orthopaedic assessment.',
    symptoms: [
      'Pain when walking short distances or climbing stairs',
      'Difficulty getting up from a chair or sitting cross-legged',
      'Knee stiffness that reduces bending',
      'Swelling or warmth in the joint',
      'Reliance on painkillers for daily comfort',
      'Increasing bow-leg or knock-knee shape',
    ],
    procedureTitle: 'Knee Replacement: Step by Step',
    procedureIntro: 'A general outline to help you prepare for conversations with your surgeon.',
    procedure: [
      { title: 'Evaluation', text: 'Clinical examination, X-rays and blood tests help confirm the diagnosis and check that you are fit for surgery.' },
      { title: 'Anaesthesia', text: 'The anaesthesia team discusses the safest type of anaesthesia and pain control for you.' },
      { title: 'Resurfacing the joint', text: 'The surgeon removes damaged cartilage and a thin layer of bone, then fits the implant components.' },
      { title: 'Early mobilisation', text: 'After surgery, the team helps you start moving and walking with support, following a structured rehabilitation plan.' },
    ],
    benefits: [
      { title: 'Pain relief', text: 'Many patients experience meaningful reduction in arthritis pain after recovery.' },
      { title: 'Improved mobility', text: 'Replacing worn surfaces can make walking and daily tasks easier.' },
      { title: 'Better alignment', text: 'Surgery can help correct deformity caused by uneven joint wear.' },
    ],
    recovery: [
      'Rehabilitation usually begins soon after surgery. Physiotherapy focuses on bending and straightening the knee, strengthening the thigh muscles and improving walking.',
      'Recovery time differs from person to person. Your surgeon will guide when you can return to activities such as driving, work or travel based on your progress.',
    ],
    aftercare: [
      'Do your prescribed knee exercises every day',
      'Use ice and elevation as advised to manage swelling',
      'Make your home safer: remove loose rugs and keep walkways clear',
      'Avoid kneeling or high-impact activities unless cleared by your surgeon',
      'Maintain a healthy weight to protect the new joint',
      'Inform your doctor about any planned dental or other procedures',
    ],
    whenToConsult: [
      'Knee pain or stiffness has continued for more than a few weeks',
      'Pain limits walking, work or sleep',
      'Your knee looks swollen, deformed or feels unstable',
      'Previous treatments are no longer effective',
    ],
    faqs: [
      { q: 'What is the difference between total and partial knee replacement?', a: 'Total knee replacement resurfaces all main parts of the joint. Partial knee replacement replaces only the damaged compartment and may be suitable when arthritis is limited to one area.' },
      { q: 'At what age can knee replacement be done?', a: 'There is no fixed age. The decision depends on symptoms, joint damage, overall health and how much the condition affects daily life.' },
      { q: 'Can I avoid surgery?', a: 'Many people manage knee arthritis with medicines, exercise, physiotherapy, weight control and lifestyle changes. Surgery is considered when these are no longer enough.' },
      { q: 'How long does a knee implant last?', a: 'Implant lifespan varies with activity level, body weight, bone quality and other factors. Your surgeon can explain what to expect in your case.' },
      { q: 'Is robotic knee replacement an option?', a: 'Robotic assistance is one technique for knee replacement. Read our robotic knee replacement page and ask your surgeon whether it is suitable for you.' },
    ],
    related: ['robotic-knee-replacement', 'hip-replacement', 'arthroscopy-sports-injury'],
    ctaTitle: 'Talk to an Orthopaedic Surgeon About Your Knee',
  },

  'hip-replacement': {
    name: 'Hip Replacement',
    h1: 'Hip Replacement Surgery in Jodhpur',
    metaTitle: 'Hip Replacement Surgery in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Find out when hip replacement may be recommended, how the procedure works, and what recovery and rehabilitation involve. Consult our orthopaedic team in Jodhpur.',
    cardText: 'Replacement of a painful, damaged hip joint to help restore comfortable movement.',
    bodyLocation: 'Hip',
    image: null,
    imageAlt: '',
    intro:
      'Hip replacement surgery replaces a worn or damaged hip joint with an artificial ball and socket. It may be advised when hip pain and stiffness seriously affect walking, sleep and everyday life.',
    overview: [
      'The hip is a ball-and-socket joint: the rounded head of the thigh bone sits in a cup-shaped socket in the pelvis. When the cartilage lining this joint is damaged, movement becomes painful and restricted.',
      'In total hip replacement, the damaged socket is lined with a new cup and the head of the thigh bone is replaced with a ball attached to a stem. In some situations, such as certain hip fractures, only the ball may be replaced (hemiarthroplasty).',
      'Your orthopaedic surgeon will recommend the most appropriate type of operation after examining you and reviewing your imaging.',
    ],
    whoBenefits: [
      'People with hip osteoarthritis that limits walking or daily tasks',
      'Patients with avascular necrosis (loss of blood supply to the hip bone)',
      'Some patients with fractures of the upper thigh bone near the hip',
      'People with inflammatory arthritis or hip problems from childhood',
    ],
    symptomsTitle: 'Common Reasons for Hip Evaluation',
    symptomsIntro: 'Hip problems are often felt in the groin, thigh or buttock, and sometimes in the knee.',
    symptoms: [
      'Groin or thigh pain when walking or standing',
      'Stiffness that makes putting on shoes or socks difficult',
      'Limping or needing support to walk',
      'Pain at night or when resting',
      'Reduced range of hip movement',
      'Hip pain after a fall in older adults',
    ],
    procedureTitle: 'Overview of Hip Replacement',
    procedureIntro: 'Your surgeon will tailor the plan to your hip and health needs.',
    procedure: [
      { title: 'Assessment', text: 'History, examination, X-rays and medical tests help confirm the diagnosis and prepare you for surgery.' },
      { title: 'Anaesthesia and approach', text: 'After anaesthesia, the surgeon reaches the hip joint through a carefully planned incision.' },
      { title: 'Replacing the joint', text: 'The damaged ball and socket are removed and replaced with implant components sized for your hip.' },
      { title: 'Rehabilitation', text: 'The care team helps you stand and walk with support and teaches exercises and safe movements for recovery.' },
    ],
    benefits: [
      { title: 'Reduced hip pain', text: 'Replacing the damaged joint surfaces may substantially reduce arthritis pain.' },
      { title: 'Easier walking', text: 'Improved movement can help with walking, stairs and daily routines.' },
      { title: 'Better sleep and comfort', text: 'Many patients find rest more comfortable once hip pain is reduced.' },
    ],
    recovery: [
      'Early movement is encouraged after hip replacement. Physiotherapy helps strengthen the muscles around the hip and improve balance and walking.',
      'Your team may give you specific guidance about positions to avoid for a period of time, depending on the surgical approach. Recovery speed differs for each person.',
    ],
    aftercare: [
      'Follow hip precautions advised by your surgeon',
      'Use walking aids until you are told it is safe to stop',
      'Use a raised toilet seat or firm chair if recommended',
      'Continue home exercises to build strength and balance',
      'Prevent falls by keeping floors dry and well lit',
      'Seek advice quickly for increased pain, wound problems or leg swelling',
    ],
    whenToConsult: [
      'Hip, groin or thigh pain has lasted several weeks',
      'Walking distance has reduced because of hip pain',
      'You cannot bear weight after a fall',
      'Pain continues despite medicines and physiotherapy',
    ],
    faqs: [
      { q: 'What is the difference between total hip replacement and hemiarthroplasty?', a: 'Total hip replacement replaces both the ball and the socket. Hemiarthroplasty replaces only the ball and is often used for certain hip fractures.' },
      { q: 'Why does hip arthritis cause knee pain?', a: 'Nerves around the hip can refer pain to the thigh and knee, so a knee ache can sometimes come from the hip. An examination helps find the true source.' },
      { q: 'Will I be able to walk after hip replacement?', a: 'Most patients begin walking with support soon after surgery under supervision. Progress depends on individual health and rehabilitation.' },
      { q: 'Are there movements to avoid after surgery?', a: 'Your surgeon may advise certain precautions for a few weeks, depending on the surgical approach used. Follow the specific instructions you receive.' },
      { q: 'Is hip replacement used for fractures?', a: 'Some hip fractures in older adults are treated with partial or total hip replacement. The choice depends on the fracture type and the patient’s health.' },
    ],
    related: ['knee-replacement', 'fracture-trauma-care', 'robotic-knee-replacement'],
    ctaTitle: 'Get Your Hip Pain Assessed',
  },

  'arthroscopy-sports-injury': {
    name: 'Arthroscopy & Sports Injury',
    h1: 'Arthroscopy and Sports Injury Treatment in Jodhpur',
    metaTitle: 'Arthroscopy & Sports Injuries Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Ligament tears, meniscus injuries, shoulder problems and more. Learn about sports injury evaluation, non-surgical care and keyhole arthroscopy in Jodhpur.',
    cardText: 'Evaluation and treatment of ligament, cartilage and joint injuries, including keyhole surgery when needed.',
    bodyLocation: 'Knee, shoulder and other joints',
    image: null,
    imageAlt: '',
    intro:
      'Sports and activity-related injuries can affect ligaments, tendons, cartilage and joints. Many improve with non-surgical care, while some may benefit from arthroscopy, a minimally invasive keyhole procedure.',
    overview: [
      'Arthroscopy allows a surgeon to look inside a joint through small incisions using a thin camera called an arthroscope. Fine instruments inserted through other small openings can then be used to repair or remove damaged tissue.',
      'It is most commonly used for the knee and shoulder, and in selected cases for other joints. Because the incisions are small, arthroscopy is described as a minimally invasive approach.',
      'Not every sports injury requires surgery. Rest, activity modification, bracing, medicines and physiotherapy are often the first step. Your orthopaedic doctor will advise surgery only when it is likely to help.',
    ],
    whoBenefits: [
      'Athletes and active people with ligament injuries such as ACL or PCL tears',
      'People with meniscus tears causing locking, catching or swelling',
      'Patients with shoulder dislocation, instability or rotator cuff problems',
      'Anyone with joint pain after a twisting or impact injury that is not settling',
    ],
    symptomsTitle: 'Common Sports and Activity Injuries',
    symptomsIntro: 'These problems may occur during sport, gym training, work or everyday activities.',
    symptoms: [
      'Anterior cruciate ligament (ACL) and other knee ligament injuries',
      'Meniscus (knee cartilage) tears',
      'Recurrent shoulder dislocation or instability',
      'Rotator cuff tears and shoulder impingement',
      'Ankle sprains that do not heal or keep recurring',
      'Tendon problems such as tennis elbow or jumper’s knee',
    ],
    procedureTitle: 'From Evaluation to Treatment',
    procedureIntro: 'Treatment depends on the type and severity of injury, your activity goals and examination findings.',
    procedure: [
      { title: 'Clinical examination', text: 'The doctor checks stability, movement and tenderness, and asks how the injury happened.' },
      { title: 'Imaging', text: 'X-rays or an MRI may be advised to assess ligaments, cartilage and bone.' },
      { title: 'Non-surgical care', text: 'Many injuries are treated with rest, bracing, medicines and a guided physiotherapy programme.' },
      { title: 'Arthroscopy when needed', text: 'If surgery is advised, keyhole techniques may be used to repair or reconstruct damaged structures.' },
    ],
    benefits: [
      { title: 'Smaller incisions', text: 'Arthroscopy uses small cuts compared with traditional open surgery.' },
      { title: 'Direct view of the joint', text: 'The camera lets the surgeon see and treat problems inside the joint.' },
      { title: 'Structured return to activity', text: 'Combined with rehabilitation, treatment aims to help you return to activity safely.' },
    ],
    recovery: [
      'Recovery after a sports injury depends on the structure involved and whether surgery was needed. A ligament reconstruction usually involves a longer, staged rehabilitation than a simple arthroscopic clean-up.',
      'Returning to sport too early can risk re-injury. Your doctor and physiotherapist will guide each stage based on strength, stability and confidence.',
    ],
    aftercare: [
      'Follow the rehabilitation programme stage by stage',
      'Use braces or slings exactly as advised',
      'Control swelling with rest, ice and elevation',
      'Avoid twisting or contact sports until cleared',
      'Work on strength, balance and flexibility',
      'Report increasing pain, swelling or instability',
    ],
    whenToConsult: [
      'You heard a pop and the joint swelled soon after an injury',
      'Your knee locks, catches or gives way',
      'Your shoulder has slipped out of place',
      'Pain prevents you from returning to sport or exercise after a few weeks',
    ],
    faqs: [
      { q: 'Does every ligament tear need surgery?', a: 'No. Treatment depends on which ligament is injured, the severity, your age and activity level. Some tears are managed with physiotherapy and bracing.' },
      { q: 'What is arthroscopy used for?', a: 'Arthroscopy can be used to diagnose and treat problems inside a joint, such as meniscus tears, ligament injuries, loose fragments and some shoulder conditions.' },
      { q: 'Should I get an MRI immediately after an injury?', a: 'Not always. A clinical examination comes first; your doctor will advise whether an MRI is needed.' },
      { q: 'When can I return to sport?', a: 'This varies widely with the injury and treatment. Your doctor and physiotherapist will advise based on your recovery milestones.' },
      { q: 'Is arthroscopy only for athletes?', a: 'No. Anyone with a suitable joint problem, whatever their activity level, may be evaluated for arthroscopy.' },
    ],
    related: ['knee-replacement', 'fracture-trauma-care', 'pediatric-orthopedics'],
    ctaTitle: 'Get Your Sports Injury Evaluated',
  },

  'spine-surgery': {
    name: 'Spine Surgery',
    h1: 'Spine Surgery and Spine Care in Jodhpur',
    metaTitle: 'Spine Surgery in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Back pain, slip disc, sciatica and spinal stenosis: learn how spine conditions are evaluated and when surgery may be considered. Consult our team in Jodhpur.',
    cardText: 'Assessment and treatment of back and neck conditions, with surgery considered when appropriate.',
    bodyLocation: 'Spine',
    image: '/s1.jpg',
    imageAlt: 'Hands applying manual therapy to a patient’s lower back',
    intro:
      'Spine conditions range from short-lived back strain to nerve compression that needs specialist care. Most back pain improves without surgery; spine surgery may be considered after careful diagnosis and clinical evaluation.',
    overview: [
      'The spine is made up of vertebrae separated by cushioning discs, with the spinal cord and nerves running through it. Problems with discs, joints, bones or nerves can cause pain in the back or neck, and sometimes symptoms in the arms or legs.',
      'Treatment usually begins with non-surgical options such as activity changes, medicines, physiotherapy and posture correction. Surgery may be discussed when nerve compression, instability or structural problems cause persistent symptoms or neurological weakness.',
      'Every spine condition is different. The information on this page is general and cannot replace an individual assessment by a qualified spine specialist.',
    ],
    whoBenefits: [
      'People with slip disc (disc herniation) and leg pain that does not settle',
      'Patients with spinal stenosis causing leg pain or heaviness when walking',
      'People with spinal instability or certain spinal deformities',
      'Patients with spine injuries or fractures needing specialist evaluation',
    ],
    symptomsTitle: 'Spine Symptoms That Need Evaluation',
    symptomsIntro: 'Seek urgent medical care for sudden weakness, loss of bladder or bowel control, or numbness around the groin.',
    symptoms: [
      'Back or neck pain lasting more than a few weeks',
      'Pain spreading down the leg (sciatica) or into the arm',
      'Numbness, tingling or weakness in the limbs',
      'Difficulty walking or standing for long periods',
      'Back pain after a fall or accident',
      'Changes in posture or spinal shape',
    ],
    procedureTitle: 'How Spine Conditions Are Evaluated and Treated',
    procedureIntro: 'The right treatment depends on an accurate diagnosis.',
    procedure: [
      { title: 'Detailed history and examination', text: 'The doctor checks posture, movement, reflexes, strength and sensation to locate the problem.' },
      { title: 'Investigations', text: 'X-rays, MRI or other tests may be advised to understand the cause of symptoms.' },
      { title: 'Conservative management', text: 'Many patients are treated first with medicines, physiotherapy, posture advice and activity modification.' },
      { title: 'Surgery when indicated', text: 'If surgery is recommended, the surgeon explains the procedure, its aims, risks and alternatives before you decide.' },
    ],
    benefits: [
      { title: 'Nerve decompression', text: 'Surgery can relieve pressure on compressed nerves in selected patients.' },
      { title: 'Spinal stability', text: 'Some procedures aim to stabilise segments of the spine that move abnormally.' },
      { title: 'Improved function', text: 'The goal of treatment is to help reduce symptoms and improve daily function.' },
    ],
    recovery: [
      'Recovery after spine treatment depends on the condition and the type of procedure. Physiotherapy often focuses on core strength, posture and safe movement patterns.',
      'Your spine specialist will guide when it is safe to resume sitting for long periods, lifting, driving and work.',
    ],
    aftercare: [
      'Follow advice on lifting, bending and twisting',
      'Maintain good posture when sitting and standing',
      'Walk regularly as advised to support recovery',
      'Continue core-strengthening exercises',
      'Use a supportive mattress and chair',
      'Report new weakness, numbness or bladder changes immediately',
    ],
    whenToConsult: [
      'Back or neck pain has not improved after a few weeks',
      'Leg or arm pain, numbness or weakness is present',
      'Pain followed a fall, accident or sports injury',
      'Urgently: loss of bladder or bowel control, or rapidly increasing weakness',
    ],
    faqs: [
      { q: 'Does slip disc always need surgery?', a: 'No. Many disc problems improve with time, medicines and physiotherapy. Surgery is considered for persistent symptoms or nerve problems, based on evaluation.' },
      { q: 'What is sciatica?', a: 'Sciatica is pain that travels from the lower back down the leg, usually caused by irritation or compression of a nerve root.' },
      { q: 'When is back pain an emergency?', a: 'Seek urgent care for back pain with loss of bladder or bowel control, numbness around the groin, sudden leg weakness, or pain after a serious injury.' },
      { q: 'Will I need an MRI?', a: 'Not everyone needs an MRI. Your doctor will decide based on your symptoms and examination findings.' },
      { q: 'Can physiotherapy help back pain?', a: 'Yes, physiotherapy is a common and often effective part of treatment for many spine conditions.' },
    ],
    related: ['fracture-trauma-care', 'arthroscopy-sports-injury', 'hip-replacement'],
    ctaTitle: 'Consult About Back or Neck Pain',
  },

  'fracture-trauma-care': {
    name: 'Fracture & Trauma Care',
    h1: 'Fracture and Trauma Care in Jodhpur',
    metaTitle: 'Fracture & Trauma Care in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'How broken bones and orthopaedic injuries are assessed and treated, from casting to surgical fixation, plus recovery guidance. Orthopaedic trauma care in Jodhpur.',
    cardText: 'Assessment and treatment of broken bones and injury-related orthopaedic problems.',
    bodyLocation: 'Bones and joints',
    image: null,
    imageAlt: '',
    intro:
      'Fractures and injuries from falls, road accidents or sport need timely orthopaedic assessment. Treatment ranges from immobilisation in a cast or splint to surgery that realigns and fixes the bone.',
    overview: [
      'A fracture is a break in a bone. It may be a simple crack, a displaced break, a break with several fragments, or an open fracture where the skin is broken. Injuries can also involve joints, ligaments and surrounding soft tissues.',
      'Orthopaedic trauma care focuses on restoring alignment, allowing the bone to heal in a good position, and helping the patient regain function.',
      'The best treatment depends on the bone involved, the fracture pattern, the patient’s age and health, and any other injuries. For life-threatening injuries, always seek the nearest emergency care first.',
    ],
    whoBenefits: [
      'People with suspected broken bones after a fall or accident',
      'Older adults with fragility fractures of the hip, wrist or spine',
      'Patients with joint injuries or dislocations',
      'People whose fracture is not healing as expected',
    ],
    symptomsTitle: 'Signs of a Possible Fracture',
    symptomsIntro: 'If you suspect a fracture, keep the area still and seek medical assessment.',
    symptoms: [
      'Severe pain after an injury',
      'Swelling, bruising or tenderness over a bone',
      'Visible deformity or abnormal angle of a limb',
      'Inability to bear weight or use the limb',
      'A grinding sensation or sound at the time of injury',
      'Numbness or tingling below the injured area',
    ],
    procedureTitle: 'Fracture Treatment Pathway',
    procedureIntro: 'A general overview of how orthopaedic injuries are managed.',
    procedure: [
      { title: 'Initial assessment', text: 'The team checks the injury, circulation and nerves, and controls pain.' },
      { title: 'Imaging', text: 'X-rays and, when needed, CT scans show the fracture pattern.' },
      { title: 'Non-surgical treatment', text: 'Many stable fractures heal with a cast, splint, brace or sling after alignment if needed.' },
      { title: 'Surgical fixation', text: 'Unstable or complex fractures may need surgery using plates, screws, rods or other fixation methods.' },
    ],
    benefits: [
      { title: 'Restored alignment', text: 'Proper treatment aims to help the bone heal in a good position.' },
      { title: 'Protected healing', text: 'Immobilisation or fixation supports the bone while it heals.' },
      { title: 'Return of function', text: 'Rehabilitation helps rebuild strength and movement after healing.' },
    ],
    recovery: [
      'Bone healing takes time and varies with the bone, the fracture type, age, nutrition and conditions such as diabetes or smoking. Regular follow-up X-rays help track progress.',
      'Physiotherapy is often needed after a cast is removed or after surgery to restore movement and strength.',
    ],
    aftercare: [
      'Keep casts and dressings clean and dry',
      'Elevate the limb to reduce swelling',
      'Do not put weight on the limb until advised',
      'Eat a balanced diet with adequate protein and calcium',
      'Avoid smoking, which can slow bone healing',
      'Seek help for increasing pain, numbness, cold or pale fingers or toes',
    ],
    whenToConsult: [
      'You suspect a broken bone after an injury',
      'Pain and swelling after a fall do not settle within a day or two',
      'A previously treated fracture remains painful or deformed',
      'An older family member has had a fall and cannot walk normally',
    ],
    faqs: [
      { q: 'How do I know if a bone is broken?', a: 'Severe pain, swelling, deformity and inability to use the limb suggest a fracture, but an X-ray is needed to confirm it.' },
      { q: 'Do all fractures need surgery?', a: 'No. Many fractures heal with a cast or splint. Surgery is considered for unstable, displaced or complex fractures.' },
      { q: 'What should I do immediately after a suspected fracture?', a: 'Keep the area still, support it, apply a cold pack wrapped in cloth, and seek medical care. For severe injuries, go to the nearest emergency department.' },
      { q: 'How long does a fracture take to heal?', a: 'Healing time varies by bone, fracture type and individual health. Your doctor will monitor healing with follow-up visits.' },
      { q: 'Will I need physiotherapy?', a: 'Many patients benefit from physiotherapy to regain movement and strength after a fracture.' },
    ],
    related: ['hip-replacement', 'spine-surgery', 'pediatric-orthopedics'],
    ctaTitle: 'Get Your Injury Assessed by an Orthopaedic Team',
  },

  'pediatric-orthopedics': {
    name: 'Pediatric Orthopaedics',
    h1: 'Pediatric Orthopaedic Care in Jodhpur',
    metaTitle: 'Pediatric Orthopaedics in Jodhpur | Bone & Joint Hospital',
    metaDescription:
      'Learn about children’s bone and joint concerns, fractures, limping and growth-related changes, and questions to ask about orthopaedic evaluation in Jodhpur.',
    cardText: 'Evaluation of bone, joint and muscle problems in children and adolescents.',
    bodyLocation: 'Musculoskeletal system',
    image: null,
    imageAlt: '',
    intro:
      'Children’s bones are still growing, so their injuries and conditions need a different approach from adults. Pediatric orthopaedic care looks at bone, joint and muscle problems in infants, children and teenagers.',
    overview: [
      'Growing bones have growth plates near their ends, which make children’s fractures heal differently and sometimes affect future growth. Some concerns, such as in-toeing or flat feet, are part of normal development and improve with time.',
      'Pediatric orthopaedic evaluation aims to tell the difference between normal variation and conditions that need monitoring or treatment, and to plan care that supports healthy growth.',
      'Treatment is often non-surgical, such as observation, casting, bracing or exercises. Surgery is considered only for specific conditions.',
    ],
    whoBenefits: [
      'Children with fractures or injuries from play or sport',
      'Children who limp or have unexplained limb pain',
      'Infants and children with foot or leg alignment concerns',
      'Teenagers with back, posture or spinal curvature concerns',
    ],
    symptomsTitle: 'Common Concerns in Children',
    symptomsIntro: 'Parents often notice these changes first. An orthopaedic evaluation can provide reassurance or a treatment plan.',
    symptoms: [
      'Fractures and growth-plate injuries',
      'Limping or refusing to walk',
      'Flat feet with pain, or in-toeing and out-toeing',
      'Bow legs or knock knees beyond the expected age',
      'Uneven shoulders or hips, or a curved spine',
      'Joint pain or swelling without a clear injury',
    ],
    procedureTitle: 'What to Expect at a Pediatric Orthopaedic Visit',
    procedureIntro: 'An educational overview of assessment and treatment planning. Contact the hospital to confirm appropriate care options for your child.',
    procedure: [
      { title: 'Talking with parents', text: 'The doctor asks about birth history, milestones, injuries and symptoms.' },
      { title: 'Gentle examination', text: 'The child’s walking, posture, joints and limbs are checked.' },
      { title: 'Investigations if needed', text: 'X-rays or other tests are advised only when they are likely to help.' },
      { title: 'Treatment plan', text: 'Options may include observation, exercises, casting, bracing or, in some conditions, surgery.' },
    ],
    benefits: [
      { title: 'Early guidance', text: 'Timely evaluation helps identify conditions that benefit from early treatment.' },
      { title: 'Growth-aware care', text: 'Treatment plans consider how a child’s bones are still developing.' },
      { title: 'Reassurance', text: 'Many concerns turn out to be normal variations, giving parents peace of mind.' },
    ],
    recovery: [
      'Children often heal faster than adults, but growth-plate injuries may need follow-up to ensure normal growth continues.',
      'Parents play an important role in recovery by helping with casts, exercises and follow-up visits.',
    ],
    aftercare: [
      'Keep casts dry and check skin around the edges',
      'Watch for swelling, colour change or increasing pain',
      'Help your child follow activity restrictions',
      'Encourage prescribed exercises in a playful way',
      'Ensure good nutrition for bone health',
      'Attend all follow-up visits, especially after growth-plate injuries',
    ],
    whenToConsult: [
      'Your child has pain, swelling or deformity after an injury',
      'Your child limps or avoids using a limb',
      'You notice uneven legs, shoulders or a curve in the back',
      'Foot or leg shape concerns persist beyond the expected age',
    ],
    faqs: [
      { q: 'Are flat feet in children a problem?', a: 'Flexible flat feet are common in young children and often improve with age. Evaluation is advised if there is pain or stiffness.' },
      { q: 'Why are children’s fractures treated differently?', a: 'Children have growth plates and more flexible bones, which affect how fractures heal and may require monitoring of future growth.' },
      { q: 'Is a limp in a child serious?', a: 'A limp can have many causes, from minor strain to conditions needing treatment. A child who limps without clear reason should be evaluated.' },
      { q: 'Will my child need surgery?', a: 'Most pediatric orthopaedic conditions are treated without surgery. Surgery is considered only for specific conditions.' },
      { q: 'When should I worry about bow legs?', a: 'Bow legs are common in toddlers. Consult a doctor if they are severe, one-sided, worsening, or persist beyond the expected age.' },
    ],
    related: ['fracture-trauma-care', 'arthroscopy-sports-injury', 'spine-surgery'],
    ctaTitle: 'Ask About Evaluation for Your Child',
  },
}

export const TREATMENT_SLUGS = Object.keys(TREATMENTS)
